### PR TITLE
Devops/page for saved recipes (PRA-94)

### PR DESCRIPTION
**Pull request by AnnaPestova1**
## One Line Description
Create a page with categories for rendering recipes (we will render recipe while receive GET method)
## Requirements

_What this code should do_
when click on nav button SAVED you'll be redirected on page with saved recipes
when click on nav button ADD RECIPE you'll be redirected on page where you can add recipe
## Notes

_Any additional info_

## Test Steps

_Instructions on how to test the changes_

## UI/UX Outcome

_Attach a screenshot here_

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

### CODE REVIEW

**Review by AnnaSolovykh — APPROVED** [review]
LGTM!

**Comment by Ekaterina-Bondareva** [comment]
There are a lot of unrelated changes here. Could you please point to exact changes related to ticket PRA-94?

**Comment by AnnaPestova1** [comment]
> There are a lot of unrelated changes here. Could you please point to exact changes related to ticket PRA-94?

Of course!
1. all new here https://github.com/Code-the-Dream-School/dd-prac-team1-front/pull/20/commits/7eff5f20ea356286bf122c957b55343c4774e177
2. _the new component SavedRecipes.tsx and changed  line 27 in index.tsx_ here: https://github.com/Code-the-Dream-School/dd-prac-team1-front/pull/20/commits/abe47866bc03630fa6859948e1e37f7b705b716c
3. all new here https://github.com/Code-the-Dream-School/dd-prac-team1-front/pull/20/commits/a736b7f5fb784031322beab773e54c3f3d13e21b

**Review by Ekaterina-Bondareva — APPROVED** [review]
Good job!

**Pull request merged**
