### PR TITLE
Dev/reset password (PRA-222)

### PR DESCRIPTION
**Pull request by AnnaPestova1**
## One Line Description
reset the password
## Requirements
- all https logic was removed by Backend.

- do not forget to update a refresh token on Backend .env  folder(see dd-team1-release-updates Slack channel) and add there JWT_RESET_PASSWORD_EXPIRES_IN=15m

_What this code should do_
reset password by sending the email with the reset password link (open the link in Google Chrome!) 
## Notes
Open the link from the letter in Google Chrome!

_Any additional info_

## Test Steps

_Instructions on how to test the changes_

## UI/UX Outcome

_Attach a screenshot here_
the button for forgetting password on Login page 
image
page for entering email:
image

the page that opens when you click the link from
image

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

### CODE REVIEW

**Review by rebekahcallkacz — CHANGES_REQUESTED** [review]
BLOCKING: When I go to `forgot password` and enter my email address, I get an error: "invalid_grant" in the toast. In mongodb, I can see that the reset token was added successfully, and I can use that token to navigate to the `reset password` page and successfully reset my password.

**Review by rebekahcallkacz — COMMENTED** [review]
I pulled the most recent version of `devops/pull-request-template` for the back end repo and added `JWT_RESET_PASSWORD_EXPIRES_IN=15m` to my `.env` file.

**Comment by AnnaPestova1** [comment]
> BLOCKING: When I go to `forgot password` and enter my email address, I get an error: "invalid_grant" in the toast. In mongodb, I can see that the reset token was added successfully, and I can use that token to navigate to the `reset password` page and successfully reset my password.

we need to update a refresh token.

**Review by rebekahcallkacz — APPROVED** [review]
I tested this with the branch `fix/https` on the backend and it worked great!

**Review by AnnaSolovykh — APPROVED** [review]

**Pull request merged**
