### PR TITLE
Dev/shopping list logic (Part2) (PRA-164)

### PR DESCRIPTION
**Pull request by AnnaPestova1**
## One Line Description
Adding the logic and improving shopping list (work starts in PRA-134)
## Requirements

_What this code should do_
This pull request prepare our shopping list to connect to backend's upcoming updates
## Notes
all added functional just imitate the options that will be add with upcoming backend updates. The code still have some preparation for recounting the serving size and this logic is waiting some updates from backend. The quantity of ingredients do not counting - it will be fixed in next pull requests with new logic from backend. So all logic of rendering amount and units will be fixed in next PRs
_Any additional info_

## Test Steps

_Instructions on how to test the changes_
after adding ingredients from single recipe go to the shopping list. Now you can add new ingredient, delete, change amount, clear the form, share. (after you would reload the page all this would disappear and the shopping list from backend would be rendering)
## UI/UX Outcome

_Attach a screenshot here_

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

### CODE REVIEW

**Review by ElenaGor8 — APPROVED** [review]
approving this. already spoke to Anna about findings upon testing:
new added ingredients don't show in the list
*to taste* unit changes to negative digits
when adding new items 0 is showing and stubborn to remove

**Comment by AnnaPestova1** [comment]
> approving this. already spoke to Anna about findings upon testing:
> new added ingredients don't show in the list
done!
> _to taste_ unit changes to negative digits
adressed to Backend
> when adding new items 0 is showing and stubborn to remove
done!

**Review by AnnaSolovykh — APPROVED** [review]
LGTM

**Comment by Ekaterina-Bondareva** [comment]
Good job! The only comment: I suppose will be great to think and fix some CSS in next PR's because when user editing his list it is not look good for me (check field right on the border, input field far away down). But maybe it was your plan. Just to think about it.
Снимок экрана 2023-08-26 в 18 34 51

**Review by Ekaterina-Bondareva — APPROVED** [review]

**Pull request merged**
