### PR TITLE
Devops/save recipe (PRA-93)

### PR DESCRIPTION
**Pull request by AnnaPestova1**
## One Line Description
create function to save the recipe to the database when click the button SAVE and show result in console

## Requirements

_What this code should do_
after successfully created recipe we need to be able to save the recipe. So, push the button SAVE and:
1. the recipe should be saved in MongoDB
2. You can see successful response in console with saved recipe
3. the button should be changed to SAVED and the heart icon should change on white color (previously the color was red, but design changed)

## Notes
Changed UseState for recipe to avoid extra code
added types for saved recipe (we will use it when we will receive API GET method)
_Any additional info_

## Test Steps

_Instructions on how to test the changes_

## UI/UX Outcome
 the button should be changed to SAVED and the heart icon should change on white color (previously the color was red, but design changed)
_Attach a screenshot here_
1. recipe in MongoDB
image

2. saved recipe in console

image

3. changed button
image

image

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

### CODE REVIEW

**Review by AnnaSolovykh — APPROVED** [review]
Great job, Anna!

**Review by Ekaterina-Bondareva — CHANGES_REQUESTED** [review]
Good job! Could you please mark it disabled  "SAVED" button when user clicked it. Because right now it allows to add the same recipe to db if user will click it one more time.

**Comment by AnnaPestova1** [comment]
> Good job! Could you please mark it disabled "SAVED" button when user clicked it. Because right now it allows to add the same recipe to db if user will click it one more time.

Thank you Ekaterina! I disabled save button when it saved. I also added disabled option on GENERATE button when a recipe is generating. Thanks for reminding about this!

**Review by Ekaterina-Bondareva — APPROVED** [review]
Great job!

**Pull request merged**
