### PR TITLE
Devops/render saved recipe(PRA-99)

### PR DESCRIPTION
**Pull request by AnnaPestova1**
## One Line Description
setup GET function and render saved recipes on page

## Requirements

_What this code should do_
render previously saved im MongoDB recipes on "saved recipe" page

## Notes

_Any additional info_

## Test Steps

_Instructions on how to test the changes_
login - create recipe with AI - save recipe - click "SAVED" navbar button - you should see all saved recipes on "SAVED RECIPE" page 

## UI/UX Outcome

_Attach a screenshot here_
image

## Checklist

- The Linear ID is in the PR title
- My code follows best practices
- Documentation is included where needed

### CODE REVIEW

**Review by AnnaSolovykh — COMMENTED** [review]
There is a warning in the console that each child in a list should have a unique "key" prop.

**Comment by AnnaPestova1** [comment]
@AnnaSolovykh I've correct the branch according changes in "parent" branch and do not see this warning, could you check it, please

**Review by AnnaSolovykh — APPROVED** [review]
Well done!

**Comment by Ekaterina-Bondareva** [comment]
Save fails with Bad request response from backend. This is probably due to the fact that AI generated recipe not according to the expected schema or conversion from AI output to schema expected by backend is not correct sometimes.
The recipe I got had the following ingredients
[
  {
    "name": "milk",
    "quantity": "1 cup",
    "unit": "cup"
  },
  {
    "name": "sugar",
    "quantity": "1 tbsp",
    "unit": "tbsp"
  },
  {
    "name": "spinach",
    "quantity": "2 cups",
    "unit": "cups"
  }
]

where quantity property also has units in addition to number. And this causes failure on backend.

**Comment by Ekaterina-Bondareva** [comment]
Sometimes recipe is generated with wrong ingredients amount like this

Sure! Here's a simple and delicious recipe for Spinach Smoothie:

Ingredients:
1 cup cup milk
1 tbsp tbsp sugar
1 cup cup spinach

Unit name is duplicated and because of that save doesn't work.

**Comment by AnnaPestova1** [comment]
> Sometimes recipe is generated with wrong ingredients amount like this
> 
> Sure! Here's a simple and delicious recipe for Spinach Smoothie:
> 
> Ingredients: 1 cup cup milk 1 tbsp tbsp sugar 1 cup cup spinach
> 
> Unit name is duplicated and because of that save doesn't work.
Thanks! 
I provided this information to our backend.

**Comment by AnnaPestova1** [comment]
@Ekaterina-Bondareva, could you please confirm that this is not 100% reproducible?
If this is the case, this seems to be a open ai issue and not front end (and maybe even not back end). Could you please approve my PR ad we will create an issue with our back end team to resolve this.

**Review by Ekaterina-Bondareva — APPROVED** [review]
Great job!

**Pull request merged**
