### PR TITLE
Devops/add typescript completes PRA-29

### PR DESCRIPTION
**Pull request by AnnaPestova1**
added TypeScript and tsconfig.json

### CODE REVIEW

**Comment by AnnaSolovykh** [comment]
Well done, Anna! It is always frightening to be the first, but you did it!

**Review by AnnaSolovykh — COMMENTED** [review]
Well done, Anna! It is always frightening to be the first, but you did it! Looks like now we have typescript installed.

**Review by rebekahcallkacz — CHANGES_REQUESTED** [review]
🎉 it's your first PR - congrats!

BLOCKING: I deleted my `node_modules` and my `package-lock.json` and then ran `npm install` but I'm getting an error that says that dependencies cannot be resolved. 

It looks like there might be issues with this version of react-scripts and TypeScript version 5. When I bumped our TypeScript version down to 4, it worked: `"typescript": "^4"`.

I'm not sure if you want to use TS v.4 or try to figure out the conflict with `react-scripts`. TS v.5 was released this year, so v.4 is an acceptable alternative.

**Comment by rebekahcallkacz** [comment]
Meant to attach this - https://github.com/facebook/create-react-app/issues/13080

**Review by rebekahcallkacz — APPROVED** [review]
LGTM (looks good to me)!

**Pull request merged**
